language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - sudo apt-get install python-matplotlib python-lxml expect-dev  # TO REMOVE ONCE MATPLOTLIB IS WHITELISTED https://github.com/travis-ci/travis-ci/issues/3901
  - pip install gitlab3
  - travis_install_nightly
  - git clone --depth=1 https://github.com/odoo/odoo-extra ~/odoo-extra

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
